using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Mobembo.cd_Back_c____.Data_Access.Entity;
using Mobembo.cd_Back_c____.Security;

namespace Mobembo.cd_Back_c____.Validation
{
    public class DonneesDB
    {
  

        public void Pays(EntityTypeBuilder<Role> pays)
        {
            pays.HasData(
                new Pays() { Id = 1, Alpha2 = "AF", Alpha3 = "AFG", Code = 4, NomEnGb = "Afghanistan", NomFrFr = "Afghanistan" },
                new Pays() { Id = 2, Alpha2 = "AL", Alpha3 = "ALB", Code = 8, NomEnGb = "Albania", NomFrFr = "Albanie" },
                new Pays() { Id = 3, Alpha2 = "AQ", Alpha3 = "ATA", Code = 10, NomEnGb = "Antarctica", NomFrFr = "Antarctique" },
                new Pays() { Id = 4, Alpha2 = "DZ", Alpha3 = "DZA", Code = 12, NomEnGb = "Algeria", NomFrFr = "Algérie" },
                new Pays() { Id = 5, Alpha2 = "AS", Alpha3 = "ASM", Code = 16, NomEnGb = "American Samoa", NomFrFr = "Samoa Américaines" },
                new Pays() { Id = 6, Alpha2 = "AD", Alpha3 = "AND", Code = 20, NomEnGb = "Andorra", NomFrFr = "Andorre" },
                new Pays() { Id = 7, Alpha2 = "AO", Alpha3 = "AGO", Code = 24, NomEnGb = "Angola", NomFrFr = "Angola" },
                new Pays() { Id = 8, Alpha2 = "AG", Alpha3 = "ATG", Code = 28, NomEnGb = "Antigua and Barbuda", NomFrFr = "Antigua-et-Barbuda" },
                new Pays() { Id = 9, Alpha2 = "AZ", Alpha3 = "AZE", Code = 31, NomEnGb = "Azerbaijan", NomFrFr = "Azerbaïdjan" },
                new Pays() { Id = 10, Alpha2 = "AR", Alpha3 = "ARG", Code = 32, NomEnGb = "Argentina", NomFrFr = "Argentine" },
                new Pays() { Id = 11, Alpha2 = "AU", Alpha3 = "AUS", Code = 36, NomEnGb = "Australia", NomFrFr = "Australie" },
                new Pays() { Id = 12, Alpha2 = "AT", Alpha3 = "AUT", Code = 40, NomEnGb = "Austria", NomFrFr = "Autriche" },
                new Pays() { Id = 13, Alpha2 = "BS", Alpha3 = "BHS", Code = 44, NomEnGb = "Bahamas", NomFrFr = "Bahamas" },
                new Pays() { Id = 14, Alpha2 = "BH", Alpha3 = "BHR", Code = 48, NomEnGb = "Bahrain", NomFrFr = "Bahreïn" },
                new Pays() { Id = 15, Alpha2 = "BD", Alpha3 = "BGD", Code = 50, NomEnGb = "Bangladesh", NomFrFr = "Bangladesh" },
                new Pays() { Id = 16, Alpha2 = "AM", Alpha3 = "ARM", Code = 51, NomEnGb = "Armenia", NomFrFr = "Arménie" },
                new Pays() { Id = 17, Alpha2 = "BB", Alpha3 = "BRB", Code = 52, NomEnGb = "Barbados", NomFrFr = "Barbade" },
                new Pays() { Id = 18, Alpha2 = "BE", Alpha3 = "BEL", Code = 56, NomEnGb = "Belgium", NomFrFr = "Belgique" },
                new Pays() { Id = 19, Alpha2 = "BM", Alpha3 = "BMU", Code = 60, NomEnGb = "Bermuda", NomFrFr = "Bermudes" },
                new Pays() { Id = 20, Alpha2 = "BT", Alpha3 = "BTN", Code = 64, NomEnGb = "Bhutan", NomFrFr = "Bhoutan" },
                new Pays() { Id = 21, Alpha2 = "BO", Alpha3 = "BOL", Code = 68, NomEnGb = "Bolivia", NomFrFr = "Bolivie" },
                new Pays() { Id = 22, Alpha2 = "BA", Alpha3 = "BIH", Code = 70, NomEnGb = "Bosnia and Herzegovina", NomFrFr = "Bosnie-Herzégovine" },
                new Pays() { Id = 23, Alpha2 = "BW", Alpha3 = "BWA", Code = 72, NomEnGb = "Botswana", NomFrFr = "Botswana" },
                new Pays() { Id = 24, Alpha2 = "BV", Alpha3 = "BVT", Code = 74, NomEnGb = "Bouvet Island", NomFrFr = "Île Bouvet" },
                new Pays() { Id = 25, Alpha2 = "BR", Alpha3 = "BRA", Code = 76, NomEnGb = "Brazil", NomFrFr = "Brésil" },
                new Pays() { Id = 26, Alpha2 = "BZ", Alpha3 = "BLZ", Code = 84, NomEnGb = "Belize", NomFrFr = "Belize" },
                new Pays() { Id = 27, Alpha2 = "IO", Alpha3 = "IOT", Code = 86, NomEnGb = "British Indian Ocean Territory", NomFrFr = "Territoire Britannique de l\"Océan Indien" },
                new Pays() { Id = 28, Alpha2 = "SB", Alpha3 = "SLB", Code = 90, NomEnGb = "Solomon Islands", NomFrFr = "Îles Salomon" },
                new Pays() { Id = 29, Alpha2 = "VG", Alpha3 = "VGB", Code = 92, NomEnGb = "British Virgin Islands", NomFrFr = "Îles Vierges Britanniques" },
                new Pays() { Id = 30, Alpha2 = "BN", Alpha3 = "BRN", Code = 96, NomEnGb = "Brunei Darussalam", NomFrFr = "Brunéi Darussalam" },
                new Pays() { Id = 31, Alpha2 = "BG", Alpha3 = "BGR", Code = 100, NomEnGb = "Bulgaria", NomFrFr = "Bulgarie" },
                new Pays() { Id = 32, Alpha2 = "MM", Alpha3 = "MMR", Code = 104, NomEnGb = "Myanmar", NomFrFr = "Myanmar" },
                new Pays() { Id = 33, Alpha2 = "BI", Alpha3 = "BDI", Code = 108, NomEnGb = "Burundi", NomFrFr = "Burundi" },
                new Pays() { Id = 34, Alpha2 = "BY", Alpha3 = "BLR", Code = 112, NomEnGb = "Belarus", NomFrFr = "Bélarus" },
                new Pays() { Id = 35, Alpha2 = "KH", Alpha3 = "KHM", Code = 116, NomEnGb = "Cambodia", NomFrFr = "Cambodge" },
                new Pays() { Id = 36, Alpha2 = "CM", Alpha3 = "CMR", Code = 120, NomEnGb = "Cameroon", NomFrFr = "Cameroun" },
                new Pays() { Id = 37, Alpha2 = "CA", Alpha3 = "CAN", Code = 124, NomEnGb = "Canada", NomFrFr = "Canada" },
                new Pays() { Id = 38, Alpha2 = "CV", Alpha3 = "CPV", Code = 132, NomEnGb = "Cape Verde", NomFrFr = "Cap-vert" },
                new Pays() { Id = 39, Alpha2 = "KY", Alpha3 = "CYM", Code = 136, NomEnGb = "Cayman Islands", NomFrFr = "Îles Caïmanes" },
                new Pays() { Id = 40, Alpha2 = "CF", Alpha3 = "CAF", Code = 140, NomEnGb = "Central African", NomFrFr = "République Centrafricaine" },
                new Pays() { Id = 41, Alpha2 = "LK", Alpha3 = "LKA", Code = 144, NomEnGb = "Sri Lanka", NomFrFr = "Sri Lanka" },
                new Pays() { Id = 42, Alpha2 = "TD", Alpha3 = "TCD", Code = 148, NomEnGb = "Chad", NomFrFr = "Tchad" },
                new Pays() { Id = 43, Alpha2 = "CL", Alpha3 = "CHL", Code = 152, NomEnGb = "Chile", NomFrFr = "Chili" },
                new Pays() { Id = 44, Alpha2 = "CN", Alpha3 = "CHN", Code = 156, NomEnGb = "China", NomFrFr = "Chine" },
                new Pays() { Id = 45, Alpha2 = "TW", Alpha3 = "TWN", Code = 158, NomEnGb = "Taiwan", NomFrFr = "Taïwan" },
                new Pays() { Id = 46, Alpha2 = "CX", Alpha3 = "CXR", Code = 162, NomEnGb = "Christmas Island", NomFrFr = "Île Christmas" },
                new Pays() { Id = 47, Alpha2 = "CC", Alpha3 = "CCK", Code = 166, NomEnGb = "Cocos {Keeling} Islands", NomFrFr = "Îles Cocos {Keeling}" },
                new Pays() { Id = 48, Alpha2 = "CO", Alpha3 = "COL", Code = 170, NomEnGb = "Colombia", NomFrFr = "Colombie" },
                new Pays() { Id = 49, Alpha2 = "KM", Alpha3 = "COM", Code = 174, NomEnGb = "Comoros", NomFrFr = "Comores" },
                new Pays() { Id = 50, Alpha2 = "YT", Alpha3 = "MYT", Code = 175, NomEnGb = "Mayotte", NomFrFr = "Mayotte" },
                new Pays() { Id = 51, Alpha2 = "CG", Alpha3 = "COG", Code = 178, NomEnGb = "Republic of the Congo", NomFrFr = "République du Congo" },
                new Pays() { Id = 52, Alpha2 = "CD", Alpha3 = "COD", Code = 180, NomEnGb = "The Democratic Republic Of The Congo", NomFrFr = "République Démocratique du Congo" },
                new Pays() { Id = 53, Alpha2 = "CK", Alpha3 = "COK", Code = 184, NomEnGb = "Cook Islands", NomFrFr = "Îles Cook" },
                new Pays() { Id = 54, Alpha2 = "CR", Alpha3 = "CRI", Code = 188, NomEnGb = "Costa Rica", NomFrFr = "Costa Rica" },
                new Pays() { Id = 55, Alpha2 = "HR", Alpha3 = "HRV", Code = 191, NomEnGb = "Croatia", NomFrFr = "Croatie" },
                new Pays() { Id = 56, Alpha2 = "CU", Alpha3 = "CUB", Code = 192, NomEnGb = "Cuba", NomFrFr = "Cuba" },
                new Pays() { Id = 57, Alpha2 = "CY", Alpha3 = "CYP", Code = 196, NomEnGb = "Cyprus", NomFrFr = "Chypre" },
                new Pays() { Id = 58, Alpha2 = "CZ", Alpha3 = "CZE", Code = 203, NomEnGb = "Czech Republic", NomFrFr = "République Tchèque" },
                new Pays() { Id = 59, Alpha2 = "BJ", Alpha3 = "BEN", Code = 204, NomEnGb = "Benin", NomFrFr = "Bénin" },
                new Pays() { Id = 60, Alpha2 = "DK", Alpha3 = "DNK", Code = 208, NomEnGb = "Denmark", NomFrFr = "Danemark" },
                new Pays() { Id = 61, Alpha2 = "DM", Alpha3 = "DMA", Code = 212, NomEnGb = "Dominica", NomFrFr = "Dominique" },
                new Pays() { Id = 62, Alpha2 = "DO", Alpha3 = "DOM", Code = 214, NomEnGb = "Dominican Republic", NomFrFr = "République Dominicaine" },
                new Pays() { Id = 63, Alpha2 = "EC", Alpha3 = "ECU", Code = 218, NomEnGb = "Ecuador", NomFrFr = "Équateur" },
                new Pays() { Id = 64, Alpha2 = "SV", Alpha3 = "SLV", Code = 222, NomEnGb = "El Salvador", NomFrFr = "NomFrFr=El Salvador" },
                new Pays() { Id = 65, Alpha2 = "GQ", Alpha3 = "GNQ", Code = 226, NomEnGb = "Equatorial Guinea", NomFrFr = "Guinée Équatoriale" },
                new Pays() { Id = 66, Alpha2 = "ET", Alpha3 = "ETH", Code = 231, NomEnGb = "Ethiopia", NomFrFr = "Éthiopie" },
                new Pays() { Id = 67, Alpha2 = "ER", Alpha3 = "ERI", Code = 232, NomEnGb = "Eritrea", NomFrFr = "Érythrée" },
                new Pays() { Id = 68, Alpha2 = "EE", Alpha3 = "EST", Code = 233, NomEnGb = "Estonia", NomFrFr = "Estonie" },
                new Pays() { Id = 69, Alpha2 = "FO", Alpha3 = "FRO", Code = 234, NomEnGb = "Faroe Islands", NomFrFr = "Îles Féroé" },
                new Pays() { Id = 70, Alpha2 = "FK", Alpha3 = "FLK", Code = 238, NomEnGb = "Falkland Islands", NomFrFr = "Îles {malvinas} Falkland" },
                new Pays() { Id = 71, Alpha2 = "GS", Alpha3 = "SGS", Code = 239, NomEnGb = "South Georgia and the South Sandwich Islands", NomFrFr = "Géorgie du Sud et les Îles Sandwich du Sud" },
                new Pays() { Id = 72, Alpha2 = "FJ", Alpha3 = "FJI", Code = 242, NomEnGb = "Fiji", NomFrFr = "Fidji" },
                new Pays() { Id = 73, Alpha2 = "FI", Alpha3 = "FIN", Code = 246, NomEnGb = "Finland", NomFrFr = "Finlande" },
                new Pays() { Id = 74, Alpha2 = "AX", Alpha3 = "ALA", Code = 248, NomEnGb = "Åland Islands", NomFrFr = "Îles Åland" },
                new Pays() { Id = 75, Alpha2 = "FR", Alpha3 = "FRA", Code = 250, NomEnGb = "France", NomFrFr = "France" },
                new Pays() { Id = 76, Alpha2 = "GF", Alpha3 = "GUF", Code = 254, NomEnGb = "French Guiana", NomFrFr = "Guyane Française" },
                new Pays() { Id = 77, Alpha2 = "PF", Alpha3 = "PYF", Code = 258, NomEnGb = "French Polynesia", NomFrFr = "Polynésie Française" },
                new Pays() { Id = 78, Alpha2 = "TF", Alpha3 = "ATF", Code = 260, NomEnGb = "French Southern Territories", NomFrFr = "Terres Australes Françaises" },
                new Pays() { Id = 79, Alpha2 = "DJ", Alpha3 = "DJI", Code = 262, NomEnGb = "Djibouti", NomFrFr = "Djibouti" },
                new Pays() { Id = 80, Alpha2 = "GA", Alpha3 = "GAB", Code = 266, NomEnGb = "Gabon", NomFrFr = "Gabon" },
                new Pays() { Id = 81, Alpha2 = "GE", Alpha3 = "GEO", Code = 268, NomEnGb = "Georgia", NomFrFr = "Géorgie" },
                new Pays() { Id = 82, Alpha2 = "GM", Alpha3 = "GMB", Code = 270, NomEnGb = "Gambia", NomFrFr = "Gambie" },
                new Pays() { Id = 83, Alpha2 = "PS", Alpha3 = "PSE", Code = 275, NomEnGb = "Occupied Palestinian Territory", NomFrFr = "Territoire Palestinien Occupé" },
                new Pays() { Id = 84, Alpha2 = "DE", Alpha3 = "DEU", Code = 276, NomEnGb = "Germany", NomFrFr = "Allemagne" },
                new Pays() { Id = 85, Alpha2 = "GH", Alpha3 = "GHA", Code = 288, NomEnGb = "Ghana", NomFrFr = "Ghana" },
                new Pays() { Id = 86, Alpha2 = "GI", Alpha3 = "GIB", Code = 292, NomEnGb = "Gibraltar", NomFrFr = "Gibraltar" },
                new Pays() { Id = 87, Alpha2 = "KI", Alpha3 = "KIR", Code = 296, NomEnGb = "Kiribati", NomFrFr = "Kiribati" },
                new Pays() { Id = 88, Alpha2 = "GR", Alpha3 = "GRC", Code = 300, NomEnGb = "Greece", NomFrFr = "Grèce" },
                new Pays() { Id = 89, Alpha2 = "GL", Alpha3 = "GRL", Code = 304, NomEnGb = "Greenland", NomFrFr = "Groenland" },
                new Pays() { Id = 90, Alpha2 = "GD", Alpha3 = "GRD", Code = 308, NomEnGb = "Grenada", NomFrFr = "Grenade" },
                new Pays() { Id = 91, Alpha2 = "GP", Alpha3 = "GLP", Code = 312, NomEnGb = "Guadeloupe", NomFrFr = "Guadeloupe" },
                new Pays() { Id = 92, Alpha2 = "GU", Alpha3 = "GUM", Code = 316, NomEnGb = "Guam", NomFrFr = "Guam" },
                new Pays() { Id = 93, Alpha2 = "GT", Alpha3 = "GTM", Code = 320, NomEnGb = "Guatemala", NomFrFr = "Guatemala" },
                new Pays() { Id = 94, Alpha2 = "GN", Alpha3 = "GIN", Code = 324, NomEnGb = "Guinea", NomFrFr = "Guinée" },
                new Pays() { Id = 95, Alpha2 = "GY", Alpha3 = "GUY", Code = 328, NomEnGb = "Guyana", NomFrFr = "Guyana" },
                new Pays() { Id = 96, Alpha2 = "HT", Alpha3 = "HTI", Code = 332, NomEnGb = "Haiti", NomFrFr = "Haïti" },
                new Pays() { Id = 97, Alpha2 = "HM", Alpha3 = "HMD", Code = 334, NomEnGb = "Heard Island and McDonald Islands", NomFrFr = "Îles Heard et Mcdonald" },
                new Pays() { Id = 98, Alpha2 = "VA", Alpha3 = "VAT", Code = 336, NomEnGb = "Vatican City State", NomFrFr = "Saint-Siège {état de la Cité du Vatican}" },
                new Pays() { Id = 99, Alpha2 = "HN", Alpha3 = "HND", Code = 340, NomEnGb = "Honduras", NomFrFr = "Honduras" },
                new Pays() { Id = 100, Alpha2 = "HK", Alpha3 = "HKG", Code = 344, NomEnGb = "Hong Kong", NomFrFr = "Hong-Kong" },
                new Pays() { Id = 101, Alpha2 = "HU", Alpha3 = "HUN", Code = 348, NomEnGb = "Hungary", NomFrFr = "Hongrie" },
                new Pays() { Id = 102, Alpha2 = "IS", Alpha3 = "ISL", Code = 352, NomEnGb = "Iceland", NomFrFr = "Islande" },
                new Pays() { Id = 103, Alpha2 = "IN", Alpha3 = "IND", Code = 356, NomEnGb = "India", NomFrFr = "Inde" },
                new Pays() { Id = 104, Alpha2 = "ID", Alpha3 = "IDN", Code = 360, NomEnGb = "Indonesia", NomFrFr = "Indonésie" },
                new Pays() { Id = 105, Alpha2 = "IR", Alpha3 = "IRN", Code = 364, NomEnGb = "Islamic Republic of Iran", NomFrFr = "République Islamique d\"Iran" },
                new Pays() { Id = 106, Alpha2 = "IQ", Alpha3 = "IRQ", Code = 368, NomEnGb = "Iraq", NomFrFr = "Iraq" },
                new Pays() { Id = 107, Alpha2 = "IE", Alpha3 = "IRL", Code = 372, NomEnGb = "Ireland", NomFrFr = "Irlande" },
                new Pays() { Id = 108, Alpha2 = "IL", Alpha3 = "ISR", Code = 376, NomEnGb = "Israel", NomFrFr = "Israël" },
                new Pays() { Id = 109, Alpha2 = "IT", Alpha3 = "ITA", Code = 380, NomEnGb = "Italy", NomFrFr = "Italie" },
                new Pays() { Id = 110, Alpha2 = "CI", Alpha3 = "CIV", Code = 384, NomEnGb = "Côte d\"Ivoire", NomFrFr = "Côte d\"Ivoire" },
                new Pays() { Id = 111, Alpha2 = "JM", Alpha3 = "JAM", Code = 388, NomEnGb = "Jamaica", NomFrFr = "Jamaïque" },
                new Pays() { Id = 112, Alpha2 = "JP", Alpha3 = "JPN", Code = 392, NomEnGb = "Japan", NomFrFr = "Japon" },
                new Pays() { Id = 113, Alpha2 = "KZ", Alpha3 = "KAZ", Code = 398, NomEnGb = "Kazakhstan", NomFrFr = "Kazakhstan" },
                new Pays() { Id = 114, Alpha2 = "JO", Alpha3 = "JOR", Code = 400, NomEnGb = "Jordan", NomFrFr = "Jordanie" },
                new Pays() { Id = 115, Alpha2 = "KE", Alpha3 = "KEN", Code = 404, NomEnGb = "Kenya", NomFrFr = "Kenya" },
                new Pays() { Id = 116, Alpha2 = "KP", Alpha3 = "PRK", Code = 408, NomEnGb = "Democratic People\"s Republic of Korea", NomFrFr = "République Populaire Démocratique de Corée" },
                new Pays() { Id = 117, Alpha2 = "KR", Alpha3 = "KOR", Code = 410, NomEnGb = "Republic of Korea", NomFrFr = "République de Corée" },
                new Pays() { Id = 118, Alpha2 = "KW", Alpha3 = "KWT", Code = 414, NomEnGb = "Kuwait", NomFrFr = "Koweït" },
                new Pays() { Id = 119, Alpha2 = "KG", Alpha3 = "KGZ", Code = 417, NomEnGb = "Kyrgyzstan", NomFrFr = "Kirghizistan" },
                new Pays() { Id = 120, Alpha2 = "LA", Alpha3 = "LAO", Code = 418, NomEnGb = "Lao People\"s Democratic Republic", NomFrFr = "République Démocratique Populaire Lao" },
                new Pays() { Id = 121, Alpha2 = "LB", Alpha3 = "LBN", Code = 422, NomEnGb = "Lebanon", NomFrFr = "Liban" },
                new Pays() { Id = 122, Alpha2 = "LS", Alpha3 = "LSO", Code = 426, NomEnGb = "Lesotho", NomFrFr = "Lesotho" },
                new Pays() { Id = 123, Alpha2 = "LV", Alpha3 = "LVA", Code = 428, NomEnGb = "Latvia", NomFrFr = "Lettonie" },
                new Pays() { Id = 124, Alpha2 = "LR", Alpha3 = "LBR", Code = 430, NomEnGb = "Liberia", NomFrFr = "Libéria" },
                new Pays() { Id = 125, Alpha2 = "LY", Alpha3 = "LBY", Code = 434, NomEnGb = "Libyan Arab Jamahiriya", NomFrFr = "Jamahiriya Arabe Libyenne" },
                new Pays() { Id = 126, Alpha2 = "LI", Alpha3 = "LIE", Code = 438, NomEnGb = "Liechtenstein", NomFrFr = "Liechtenstein" },
                new Pays() { Id = 127, Alpha2 = "LT", Alpha3 = "LTU", Code = 440, NomEnGb = "Lithuania", NomFrFr = "Lituanie" },
                new Pays() { Id = 128, Alpha2 = "LU", Alpha3 = "LUX", Code = 442, NomEnGb = "Luxembourg", NomFrFr = "Luxembourg" },
                new Pays() { Id = 129, Alpha2 = "MO", Alpha3 = "MAC", Code = 446, NomEnGb = "Macao", NomFrFr = "Macao" },
                new Pays() { Id = 130, Alpha2 = "MG", Alpha3 = "MDG", Code = 450, NomEnGb = "Madagascar", NomFrFr = "Madagascar" },
                new Pays() { Id = 131, Alpha2 = "MW", Alpha3 = "MWI", Code = 454, NomEnGb = "Malawi", NomFrFr = "Malawi" },
                new Pays() { Id = 132, Alpha2 = "MY", Alpha3 = "MYS", Code = 458, NomEnGb = "Malaysia", NomFrFr = "Malaisie" },
                new Pays() { Id = 133, Alpha2 = "MV", Alpha3 = "MDV", Code = 462, NomEnGb = "Maldives", NomFrFr = "Maldives" },
                new Pays() { Id = 134, Alpha2 = "ML", Alpha3 = "MLI", Code = 466, NomEnGb = "Mali", NomFrFr = "Mali" },
                new Pays() { Id = 135, Alpha2 = "MT", Alpha3 = "MLT", Code = 470, NomEnGb = "Malta", NomFrFr = "Malte" },
                new Pays() { Id = 136, Alpha2 = "MQ", Alpha3 = "MTQ", Code = 474, NomEnGb = "Martinique", NomFrFr = "Martinique" },
                new Pays() { Id = 137, Alpha2 = "MR", Alpha3 = "MRT", Code = 478, NomEnGb = "Mauritania", NomFrFr = "Mauritanie" },
                new Pays() { Id = 138, Alpha2 = "MU", Alpha3 = "MUS", Code = 480, NomEnGb = "Mauritius", NomFrFr = "Maurice" },
                new Pays() { Id = 139, Alpha2 = "MX", Alpha3 = "MEX", Code = 484, NomEnGb = "Mexico", NomFrFr = "Mexique" },
                new Pays() { Id = 140, Alpha2 = "MC", Alpha3 = "MCO", Code = 492, NomEnGb = "Monaco", NomFrFr = "Monaco" },
                new Pays() { Id = 141, Alpha2 = "MN", Alpha3 = "MNG", Code = 496, NomEnGb = "Mongolia", NomFrFr = "Mongolie" },
                new Pays() { Id = 142, Alpha2 = "MD", Alpha3 = "MDA", Code = 498, NomEnGb = "Republic of Moldova", NomFrFr = "République de Moldova" },
                new Pays() { Id = 143, Alpha2 = "MS", Alpha3 = "MSR", Code = 500, NomEnGb = "Montserrat", NomFrFr = "Montserrat" },
                new Pays() { Id = 144, Alpha2 = "MA", Alpha3 = "MAR", Code = 504, NomEnGb = "Morocco", NomFrFr = "Maroc" },
                new Pays() { Id = 145, Alpha2 = "MZ", Alpha3 = "MOZ", Code = 508, NomEnGb = "Mozambique", NomFrFr = "Mozambique" },
                new Pays() { Id = 146, Alpha2 = "OM", Alpha3 = "OMN", Code = 512, NomEnGb = "Oman", NomFrFr = "Oman" },
                new Pays() { Id = 147, Alpha2 = "NA", Alpha3 = "NAM", Code = 516, NomEnGb = "Namibia", NomFrFr = "Namibie" },
                new Pays() { Id = 148, Alpha2 = "NR", Alpha3 = "NRU", Code = 520, NomEnGb = "Nauru", NomFrFr = "Nauru" },
                new Pays() { Id = 149, Alpha2 = "NP", Alpha3 = "NPL", Code = 524, NomEnGb = "Nepal", NomFrFr = "Népal" },
                new Pays() { Id = 150, Alpha2 = "NL", Alpha3 = "NLD", Code = 528, NomEnGb = "Netherlands", NomFrFr = "Pays-Bas" },
                new Pays() { Id = 151, Alpha2 = "AN", Alpha3 = "ANT", Code = 530, NomEnGb = "Netherlands Antilles", NomFrFr = "Antilles Néerlandaises" },
                new Pays() { Id = 152, Alpha2 = "AW", Alpha3 = "ABW", Code = 533, NomEnGb = "Aruba", NomFrFr = "Aruba" },
                new Pays() { Id = 153, Alpha2 = "NC", Alpha3 = "NCL", Code = 540, NomEnGb = "New Caledonia", NomFrFr = "Nouvelle-Calédonie" },
                new Pays() { Id = 154, Alpha2 = "VU", Alpha3 = "VUT", Code = 548, NomEnGb = "Vanuatu", NomFrFr = "Vanuatu" },
                new Pays() { Id = 155, Alpha2 = "NZ", Alpha3 = "NZL", Code = 554, NomEnGb = "New Zealand", NomFrFr = "Nouvelle-Zélande" },
                new Pays() { Id = 156, Alpha2 = "NI", Alpha3 = "NIC", Code = 558, NomEnGb = "Nicaragua", NomFrFr = "Nicaragua" },
                new Pays() { Id = 157, Alpha2 = "NE", Alpha3 = "NER", Code = 562, NomEnGb = "Niger", NomFrFr = "Niger" },
                new Pays() { Id = 158, Alpha2 = "NG", Alpha3 = "NGA", Code = 566, NomEnGb = "Nigeria", NomFrFr = "Nigéria" },
                new Pays() { Id = 159, Alpha2 = "NU", Alpha3 = "NIU", Code = 570, NomEnGb = "Niue", NomFrFr = "Niué" },
                new Pays() { Id = 160, Alpha2 = "NF", Alpha3 = "NFK", Code = 574, NomEnGb = "Norfolk Island", NomFrFr = "Île Norfolk" },
                new Pays() { Id = 161, Alpha2 = "NO", Alpha3 = "NOR", Code = 578, NomEnGb = "Norway", NomFrFr = "Norvège" },
                new Pays() { Id = 162, Alpha2 = "MP", Alpha3 = "MNP", Code = 580, NomEnGb = "Northern Mariana Islands", NomFrFr = "Îles Mariannes du Nord" },
                new Pays() { Id = 163, Alpha2 = "UM", Alpha3 = "UMI", Code = 581, NomEnGb = "United States Minor Outlying Islands", NomFrFr = "Îles Mineures Éloignées des États-Unis" },
                new Pays() { Id = 164, Alpha2 = "FM", Alpha3 = "FSM", Code = 583, NomEnGb = "Federated States of Micronesia", NomFrFr = "États Fédérés de Micronésie" },
                new Pays() { Id = 165, Alpha2 = "MH", Alpha3 = "MHL", Code = 584, NomEnGb = "Marshall Islands", NomFrFr = "Îles Marshall" },
                new Pays() { Id = 166, Alpha2 = "PW", Alpha3 = "PLW", Code = 585, NomEnGb = "Palau", NomFrFr = "Palaos" },
                new Pays() { Id = 167, Alpha2 = "PK", Alpha3 = "PAK", Code = 586, NomEnGb = "Pakistan", NomFrFr = "Pakistan" },
                new Pays() { Id = 168, Alpha2 = "PA", Alpha3 = "PAN", Code = 591, NomEnGb = "Panama", NomFrFr = "Panama" },
                new Pays() { Id = 169, Alpha2 = "PG", Alpha3 = "PNG", Code = 598, NomEnGb = "Papua New Guinea", NomFrFr = "Papouasie-Nouvelle-Guinée" },
                new Pays() { Id = 170, Alpha2 = "PY", Alpha3 = "PRY", Code = 600, NomEnGb = "Paraguay", NomFrFr = "Paraguay" },
                new Pays() { Id = 171, Alpha2 = "PE", Alpha3 = "PER", Code = 604, NomEnGb = "Peru", NomFrFr = "Pérou" },
                new Pays() { Id = 172, Alpha2 = "PH", Alpha3 = "PHL", Code = 608, NomEnGb = "Philippines", NomFrFr = "Philippines" },
                new Pays() { Id = 173, Alpha2 = "PN", Alpha3 = "PCN", Code = 612, NomEnGb = "Pitcairn", NomFrFr = "Pitcairn" },
                new Pays() { Id = 174, Alpha2 = "PL", Alpha3 = "POL", Code = 616, NomEnGb = "Poland", NomFrFr = "Pologne" },
                new Pays() { Id = 175, Alpha2 = "PT", Alpha3 = "PRT", Code = 620, NomEnGb = "Portugal", NomFrFr = "Portugal" },
                new Pays() { Id = 176, Alpha2 = "GW", Alpha3 = "GNB", Code = 624, NomEnGb = "Guinea-Bissau", NomFrFr = "Guinée-Bissau" },
                new Pays() { Id = 177, Alpha2 = "TL", Alpha3 = "TLS", Code = 626, NomEnGb = "Timor-Leste", NomFrFr = "Timor-Leste" },
                new Pays() { Id = 178, Alpha2 = "PR", Alpha3 = "PRI", Code = 630, NomEnGb = "Puerto Rico", NomFrFr = "Porto Rico" },
                new Pays() { Id = 179, Alpha2 = "QA", Alpha3 = "QAT", Code = 634, NomEnGb = "Qatar", NomFrFr = "Qatar" },
                new Pays() { Id = 180, Alpha2 = "RE", Alpha3 = "REU", Code = 638, NomEnGb = "Réunion", NomFrFr = "Réunion" },
                new Pays() { Id = 181, Alpha2 = "RO", Alpha3 = "ROU", Code = 642, NomEnGb = "Romania", NomFrFr = "Roumanie" },
                new Pays() { Id = 182, Alpha2 = "RU", Alpha3 = "RUS", Code = 643, NomEnGb = "Russian Federation", NomFrFr = "Fédération de Russie" },
                new Pays() { Id = 183, Alpha2 = "RW", Alpha3 = "RWA", Code = 646, NomEnGb = "Rwanda", NomFrFr = "Rwanda" },
                new Pays() { Id = 184, Alpha2 = "SH", Alpha3 = "SHN", Code = 654, NomEnGb = "Saint Helena", NomFrFr = "Sainte-Hélène" },
                new Pays() { Id = 185, Alpha2 = "KN", Alpha3 = "KNA", Code = 659, NomEnGb = "Saint Kitts and Nevis", NomFrFr = "Saint-Kitts-et-Nevis" },
                new Pays() { Id = 186, Alpha2 = "AI", Alpha3 = "AIA", Code = 660, NomEnGb = "Anguilla", NomFrFr = "Anguilla" },
                new Pays() { Id = 187, Alpha2 = "LC", Alpha3 = "LCA", Code = 662, NomEnGb = "Saint Lucia", NomFrFr = "Sainte-Lucie" },
                new Pays() { Id = 188, Alpha2 = "PM", Alpha3 = "SPM", Code = 666, NomEnGb = "Saint-Pierre and Miquelon", NomFrFr = "Saint-Pierre-et-Miquelon" },
                new Pays() { Id = 189, Alpha2 = "VC", Alpha3 = "VCT", Code = 670, NomEnGb = "Saint Vincent and the Grenadines", NomFrFr = "Saint-Vincent-et-les Grenadines" },
                new Pays() { Id = 190, Alpha2 = "SM", Alpha3 = "SMR", Code = 674, NomEnGb = "San Marino", NomFrFr = "Saint-Marin" },
                new Pays() { Id = 191, Alpha2 = "ST", Alpha3 = "STP", Code = 678, NomEnGb = "Sao Tome and Principe", NomFrFr = "Sao Tomé-et-Principe" },
                new Pays() { Id = 192, Alpha2 = "SA", Alpha3 = "SAU", Code = 682, NomEnGb = "Saudi Arabia", NomFrFr = "Arabie Saoudite" },
                new Pays() { Id = 193, Alpha2 = "SN", Alpha3 = "SEN", Code = 686, NomEnGb = "Senegal", NomFrFr = "Sénégal" },
                new Pays() { Id = 194, Alpha2 = "SC", Alpha3 = "SYC", Code = 690, NomEnGb = "Seychelles", NomFrFr = "Seychelles" },
                new Pays() { Id = 195, Alpha2 = "SL", Alpha3 = "SLE", Code = 694, NomEnGb = "Sierra Leone", NomFrFr = "Sierra Leone" },
                new Pays() { Id = 196, Alpha2 = "SG", Alpha3 = "SGP", Code = 702, NomEnGb = "Singapore", NomFrFr = "Singapour" },
                new Pays() { Id = 197, Alpha2 = "SK", Alpha3 = "SVK", Code = 703, NomEnGb = "Slovakia", NomFrFr = "Slovaquie" },
                new Pays() { Id = 198, Alpha2 = "VN", Alpha3 = "VNM", Code = 704, NomEnGb = "Vietnam", NomFrFr = "Viet Nam" },
                new Pays() { Id = 199, Alpha2 = "SI", Alpha3 = "SVN", Code = 705, NomEnGb = "Slovenia", NomFrFr = "Slovénie" },
                new Pays() { Id = 200, Alpha2 = "SO", Alpha3 = "SOM", Code = 706, NomEnGb = "Somalia", NomFrFr = "Somalie" },
                new Pays() { Id = 201, Alpha2 = "ZA", Alpha3 = "ZAF", Code = 710, NomEnGb = "South Africa", NomFrFr = "Afrique du Sud" },
                new Pays() { Id = 202, Alpha2 = "ZW", Alpha3 = "ZWE", Code = 716, NomEnGb = "Zimbabwe", NomFrFr = "Zimbabwe" },
                new Pays() { Id = 203, Alpha2 = "ES", Alpha3 = "ESP", Code = 724, NomEnGb = "Spain", NomFrFr = "Espagne" },
                new Pays() { Id = 204, Alpha2 = "EH", Alpha3 = "ESH", Code = 732, NomEnGb = "Western Sahara", NomFrFr = "Sahara Occidental" },
                new Pays() { Id = 205, Alpha2 = "SD", Alpha3 = "SDN", Code = 736, NomEnGb = "Sudan", NomFrFr = "Soudan" },
                new Pays() { Id = 206, Alpha2 = "SR", Alpha3 = "SUR", Code = 740, NomEnGb = "Suriname", NomFrFr = "Suriname" },
                new Pays() { Id = 207, Alpha2 = "SJ", Alpha3 = "SJM", Code = 744, NomEnGb = "Svalbard and Jan Mayen", NomFrFr = "Svalbard etÎle Jan Mayen" },
                new Pays() { Id = 208, Alpha2 = "SZ", Alpha3 = "SWZ", Code = 748, NomEnGb = "Swaziland", NomFrFr = "Swaziland" },
                new Pays() { Id = 209, Alpha2 = "SE", Alpha3 = "SWE", Code = 752, NomEnGb = "Sweden", NomFrFr = "Suède" },
                new Pays() { Id = 210, Alpha2 = "CH", Alpha3 = "CHE", Code = 756, NomEnGb = "Switzerland", NomFrFr = "Suisse" },
                new Pays() { Id = 211, Alpha2 = "SY", Alpha3 = "SYR", Code = 760, NomEnGb = "Syrian Arab Republic", NomFrFr = "République Arabe Syrienne" },
                new Pays() { Id = 212, Alpha2 = "TJ", Alpha3 = "TJK", Code = 762, NomEnGb = "Tajikistan", NomFrFr = "Tadjikistan" },
                new Pays() { Id = 213, Alpha2 = "TH", Alpha3 = "THA", Code = 764, NomEnGb = "Thailand", NomFrFr = "Thaïlande" },
                new Pays() { Id = 214, Alpha2 = "TG", Alpha3 = "TGO", Code = 768, NomEnGb = "Togo", NomFrFr = "Togo" },
                new Pays() { Id = 215, Alpha2 = "TK", Alpha3 = "TKL", Code = 772, NomEnGb = "Tokelau", NomFrFr = "Tokelau" },
                new Pays() { Id = 216, Alpha2 = "TO", Alpha3 = "TON", Code = 776, NomEnGb = "Tonga", NomFrFr = "Tonga" },
                new Pays() { Id = 217, Alpha2 = "TT", Alpha3 = "TTO", Code = 780, NomEnGb = "Trinidad and Tobago", NomFrFr = "Trinité-et-Tobago" },
                new Pays() { Id = 218, Alpha2 = "AE", Alpha3 = "ARE", Code = 784, NomEnGb = "United Arab Emirates", NomFrFr = "Émirats Arabes Unis" },
                new Pays() { Id = 219, Alpha2 = "TN", Alpha3 = "TUN", Code = 788, NomEnGb = "Tunisia", NomFrFr = "Tunisie" },
                new Pays() { Id = 220, Alpha2 = "TR", Alpha3 = "TUR", Code = 792, NomEnGb = "Turkey", NomFrFr = "Turquie" },
                new Pays() { Id = 221, Alpha2 = "TM", Alpha3 = "TKM", Code = 795, NomEnGb = "Turkmenistan", NomFrFr = "Turkménistan" },
                new Pays() { Id = 222, Alpha2 = "TC", Alpha3 = "TCA", Code = 796, NomEnGb = "Turks and Caicos Islands", NomFrFr = "Îles Turks et Caïques" },
                new Pays() { Id = 223, Alpha2 = "TV", Alpha3 = "TUV", Code = 798, NomEnGb = "Tuvalu", NomFrFr = "Tuvalu" },
                new Pays() { Id = 224, Alpha2 = "UG", Alpha3 = "UGA", Code = 800, NomEnGb = "Uganda", NomFrFr = "Ouganda" },
                new Pays() { Id = 225, Alpha2 = "UA", Alpha3 = "UKR", Code = 804, NomEnGb = "Ukraine", NomFrFr = "Ukraine" },
                new Pays() { Id = 226, Alpha2 = "MK", Alpha3 = "MKD", Code = 807, NomEnGb = "The Former Yugoslav Republic of Macedonia", NomFrFr = "L\"ex-République Yougoslave de Macédoine" },
                new Pays() { Id = 227, Alpha2 = "EG", Alpha3 = "EGY", Code = 818, NomEnGb = "Egypt", NomFrFr = "Égypte" },
                new Pays() { Id = 228, Alpha2 = "GB", Alpha3 = "GBR", Code = 826, NomEnGb = "United Kingdom", NomFrFr = "Royaume-Uni" },
                new Pays() { Id = 229, Alpha2 = "IM", Alpha3 = "IMN", Code = 833, NomEnGb = "Isle of Man", NomFrFr = "Île de Man" },
                new Pays() { Id = 230, Alpha2 = "TZ", Alpha3 = "TZA", Code = 834, NomEnGb = "United Republic Of Tanzania", NomFrFr = "République-Unie de Tanzanie" },
                new Pays() { Id = 231, Alpha2 = "US", Alpha3 = "USA", Code = 840, NomEnGb = "United States", NomFrFr = "États-Unis" },
                new Pays() { Id = 232, Alpha2 = "VI", Alpha3 = "VIR", Code = 850, NomEnGb = "U.S. Virgin Islands", NomFrFr = "Îles Vierges des États-Unis" },
                new Pays() { Id = 233, Alpha2 = "BF", Alpha3 = "BFA", Code = 854, NomEnGb = "Burkina Faso", NomFrFr = "Burkina Faso" },
                new Pays() { Id = 234, Alpha2 = "UY", Alpha3 = "URY", Code = 858, NomEnGb = "Uruguay", NomFrFr = "Uruguay" },
                new Pays() { Id = 235, Alpha2 = "UZ", Alpha3 = "UZB", Code = 860, NomEnGb = "Uzbekistan", NomFrFr = "Ouzbékistan" },
                new Pays() { Id = 236, Alpha2 = "VE", Alpha3 = "VEN", Code = 862, NomEnGb = "Venezuela", NomFrFr = "Venezuela" },
                new Pays() { Id = 237, Alpha2 = "WF", Alpha3 = "WLF", Code = 876, NomEnGb = "Wallis and Futuna", NomFrFr = "Wallis et Futuna" },
                new Pays() { Id = 238, Alpha2 = "WS", Alpha3 = "WSM", Code = 882, NomEnGb = "Samoa", NomFrFr = "Samoa" },
                new Pays() { Id = 239, Alpha2 = "YE", Alpha3 = "YEM", Code = 887, NomEnGb = "Yemen", NomFrFr = "Yémen" },
                new Pays() { Id = 240, Alpha2 = "CS", Alpha3 = "SCG", Code = 891, NomEnGb = "Serbia and Montenegro", NomFrFr = "Serbie-et-Monténégro" },
                new Pays() { Id = 241, Alpha2 = "ZM", Alpha3 = "ZMB", Code = 894, NomEnGb = "Zambia", NomFrFr = "Zambie" }
                );
        }


        internal void Role(EntityTypeBuilder<Role> entityTypeBuilder)
        {
            entityTypeBuilder.HasData(
                new Role() { Id = 1, NomRole = Constente.RoleAd }, 
                new Role() { Id = 2, NomRole = Constente.RoleCl }
                );
        }
    }
}
